### ISSUE TITLE
Backblaze B2 backend

### ISSUE THREAD

**Issue by prologic** [someone1/zfsbackup-go#2]
So you don't forget :D -- I'll be more than happy to test this out!

Also consider re-using [rclone](https://github.com/ncw/rclone) which has backends for many more cloud storage providers.

**Comment by someone1** [comment]
Thanks for the tip, I had forgotten about that project. I noticed that the author chose not to utilize the hash verification upon upload (at least from my quick perusal of the S3 and GCS implementations). This would not make it an ideal to use directly, but you can probably get away with using the supported `file://` target in this project to point to a mounted path from rclone (e.g. using their FUSE mounting feature). I haven't tested this myself but I'd assume it should work?

**Comment by prologic** [comment]
Probably :) I just didn't want you to have to spend too much time
reinventig wheels; borrow from their code :)

I'm okay with zfsbackup-go growing it's own b2 backend as long as its
reliable.

I'm going ot be using this thing to replace my crashplan setup from my ZFS
NAS (ZOL/ZFSOnLinux)

**Comment by someone1** [comment]
I'd be using the integration to b2 using this project: https://github.com/kurin/blazer

The project appears to be doing a good job integrating using BackBlaze's integration checklist, which is the best I could ask for other than an SDK from BackBlaze themselves.

Generally, I don't write any API integrations with a target cloud provider I'm working on integrating to the application. My integrations more/less just use the SDKs available from the cloud provider which implement best practices for integrating against their own services, this includes retry/backoff logic, resumeable or multipart upload logic, etc. I write simple wrappers for coordinating the uploads with the rest of the backup/restore processes and options passed by the user (e.g. max parallel uploads) and do my research to ensure I utilize all options available for a resilient and verified upload/download.

I'll hopefully have something in the next day or two for you to test! I'm sure you're already aware of this, but this sort of backup is block-level, not file-level like Crashplan is.

**Comment by someone1** [comment]
Release for B2 has been added with the latest release: https://github.com/someone1/zfsbackup-go/releases/tag/v0.3-rc1

Please give it a go and let me know what you think!

**Comment by prologic** [comment]
Wil ldo! Thanks!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
