### ISSUE TITLE
How are people managing deletion of older snapshots?

### ISSUE THREAD

**Issue by saurabhnanda** [someone1/zfsbackup-go#217]
The project's [TODO list](https://github.com/someone1/zfsbackup-go#todos) clearly mentions "Add delete feature". How do folks manage deletion of snapshots older than X days on the remote backend?

**Comment by someone1** [comment]
This is a case where priorities were based on the company footing the bill to have me develop the software! The need for the company was a minimum 7-year archive of the backups so the feature wouldn't even be needed by then. 

Although not perfect, most providers should have lifecycle rules so you can have files auto delete after X days. It's not the same as pruning an entire snapshot (e.g. you may delete parts of a snapshot over the course of minutes/hours depending on its size) but it mostly gets you there.

**Comment by saurabhnanda** [comment]
If I were to take a stab at implementing a delete feature, where should I start? Here's a simplistic solution I was thinking of:

- implement a command to delete the MANIFESTS of FULL snapshots between a given time range (including the chain of all incremental backups)
- use the existing `clean` command to "delete any objects in the target that are not found in the manifest files found in the target."

Does this sound like a good idea?

PS: I thought Backblaze's lifecycle rules had me covered, but I was wrong. The lifecycle rules apply to multiple versions of the _same_ file (i.e. filename shouldn't change). But zfsbackup-go creates files with different name. So, my B2 bucket storage is ballooning month-on-month!

**Comment by someone1** [comment]
The docs on Backblaze do give an example of how to auto-prune things like server logs after 8 days [here](https://www.backblaze.com/b2/docs/lifecycle_rules.html#:~:text=The%20daysFromUploadingToHiding%20setting).

```json
    {
        "daysFromHidingToDeleting": 1,
        "daysFromUploadingToHiding": 7,
        "fileNamePrefix": "logs/"
    }
```

Is this how your rule is setup?

**Comment by saurabhnanda** [comment]
That's what I thought earlier, as well. Based on the docs, it  seems like
these lifecycle rules work for files, but in my experience they work for
**file versions**. The file needs to be overwritten with the same name for
B2 to treat it as a new version.

Has your experience been different? Is there any way to make this work for
files, instead of file versions?

**Comment by saurabhnanda** [comment]
> I'm not sure it would be safe to assume we can run clean after deleting manifest files - there could be other reasons files exist in the bucket and so we should be explicit about what to delete. If you are able to identify all manifests to delete, you can then use them to identify exactly which files to delete as well.

Would you be open to a PR with this functionality? Or should I develop a standalone tool for this?

**Comment by saurabhnanda** [comment]
> That's what I thought earlier, as well. Based on the docs, it  seems like these lifecycle rules work for files, but in my experience they work for **file versions**.

I stand corrected. These lifecycle rules work for files, as well as, file versions. The subtle catch was that one had to setup a rule to first hide the file and only then delete it. Apparently, directly deleting it doesn't work because of some UX issue in the webform that one uses to setup these lifecycle rules.
