### ISSUE TITLE
Usage is always printed on error

### ISSUE THREAD

**Issue by HugoPoi** [someone1/zfsbackup-go#24]
I doesn't know if it's a bug or a feature but the command usage aka `--help` is always printed on error, its annoying for readability and for logging cron task.

**Comment by someone1** [comment]
Fixed in #26

**Comment by HugoPoi** [comment]
I will build locally to test that :-) And I have writen a little blog post about [using zfsbackup with FreeNAS](https://blog.hugopoi.net/2020/04/11/how-to-backup-freenas-zvol-to-s3-storage/)

**Comment by someone1** [comment]
I'd be very interested to hear your feedback and experience with the tool!
