### ISSUE TITLE
Remote snapshot content

### ISSUE THREAD

**Issue by jdeluyck** [someone1/zfsbackup-go#30]
Hi,

I was wondering if there is some way to figure out what is in a remote snapshot before you start downloading it again?

**Comment by someone1** [comment]
Are you referring to files within a snapshot? This is outside the scope of the project. The backups are block-level so there is no concept or idea of what data is within a snapshot.

You can probably create something rudimentary by listing all files within a dataset for a snapshot and storing the result in another bucket/system - maybe even a database:

```bash
ls -Rlad /path/to/dataset/.zfs/snapshot/snapshotname/**/* > "pool-snapshot-name.txt"
```

Then store the file near the backup (e.g. in the bucket) or in a database for reference later.

If you need file-level backups, you may be better off with cloud sync solutions or something like [restic](https://restic.net/).
