### ISSUE TITLE
[questions] Restore to a different fs

### ISSUE THREAD

**Issue by aensidhe** [someone1/zfsbackup-go#33]
Hi.

Let's say I've backed up `mimir/test` filesystem. I'd like to restore it to `mimir/test-restore` filesystem. I couldn't figure out how to do that.

Also, if there any way to support some kind of progress no send/receive?

**Comment by someone1** [comment]
What command have you been trying to use? Have you tried to pass along the `-F` parameter during the restore?

Progress is a great idea - it may be trivial to do something like `bytes processed / bytes remaining` on the receive side, but wouldn't be as straight forward on the send side.
