### ISSUE TITLE
[Feature Request] New AWS backend - EBS direct API block storage snapshots

### ISSUE THREAD

**Issue by fred-vogt** [someone1/zfsbackup-go#37]
This is new in AWS as of July-2020.

This may also allow use of 
* AWS EBS Data Lifecycle Management policies for snapshot retention
* KMS for encryption
* Cross account resource permissions

## Links
* https://aws.amazon.com/blogs/aws/new-create-snapshots-from-any-block-storage/
* EBS direct API
  * https://docs.aws.amazon.com/ebs/latest/APIReference/Welcome.html
* https://aws.amazon.com/blogs/aws/new-programmatic-access-to-ebs-snapshot-content/

**Comment by someone1** [comment]
This seems interesting! However, from my initial read, it doesn't seem like a good fit for the current feature set of this software - it seems more suitable for something that would translate a ZFS snapshot into an EBS snapshot, which I'm not sure would be compatible.

How did you envision integrating this? It doesn't appear to be a general blob storage as all other current storage targets are.

**Comment by fred-vogt** [comment]
@someone1 - good points.  I think you are correct.  Love zfsbackup-go.  Closing for now.
