### ISSUE TITLE
Issue With Receiving Encrypted Snapshot From S3 - "tag byte does not have MSB set"

### ISSUE THREAD

**Issue by acdapkus** [someone1/zfsbackup-go#39]
**Goals:**
I have setup zfsbackup-go on my zfs backup server. My intention is to use zfsbackup-go to encrypt snapshots and upload to S3. If my system fails, I plan on restoring from S3. Obvious goals, but figured I should include this.

**What Works:**
I have successfully uploaded a snapshot to S3. I have also downloaded this snapshot from S3 and restored it locally. This snapshot was _**NOT encrypted**_.

Using the same command which worked for sending unencrypted snapshots, but adding in the required encryption information, successfully uploads encrypted snapshots to S3.

**What Does NOT Work:**
Attempting to restore the encrypted snapshot from S3.

The command used to receive the S3 snapshot follows.

```
sudo AWS_ACCESS_KEY=XX AWS_REGION=XX AWS_SECRET_ACCESS_KEY=XX GOROOT=/usr/local/go /usr/local/go/zfsbackup-go receive --encryptTo a.dapkus@XX.com --signFrom a.dapkus@XX.com --publicKeyRingPath public.pgp.asc --secretKeyRingPath private.pgp.asc --auto -d tank/encryptionTest@testUpload s3://XX.backups tank

```

The debug output is as follows.

```
2020/08/17 20:20:08 Setting number of cores to: 2
2020/08/17 20:20:08 Loaded private key ring secring.asc
2020/08/17 20:20:08 Loaded public key ring pubring.asc
2020/08/17 20:20:08 Setting working directory to /root/.zfsbackup
2020/08/17 20:20:08 PGP Debug Info:
Loaded Private Keys:
        XXX
        map[Aleksander Dapkus <a.dapkus@XXX>:0xc000XXX]

Loaded Public Keys:
        XXX
        map[Aleksander Dapkus <a.dapkus@XXX>:0xc000XXX]
Enter passphrase to decrypt encryption key: 
2020/08/17 20:20:10 Limiting the number of active files to 5
2020/08/17 20:20:10 Initializing Backend s3://XXX.backups
2020/08/17 20:20:10 s3 backend: will use the Bulk restore tier when trying to restore from Glacier.
2020/08/17 20:20:10 Could not read manifest /root/.zfsbackup/cache/XXX/XXX due to error - openpgp: invalid data: tag byte does not have MSB set
```

It seems the issue revolves around this line: **Could not read manifest /root/.zfsbackup/cache/XXX/XXX due to error - openpgp: invalid data: tag byte does not have MSB set**

I have redacted some info, more than required. Let me know if I have redacted a key piece of information.

**Comment by someone1** [comment]
Hmmm - I think it may be a bug with waiting for the file to be restored from Glacier. I do have an [integration test](https://github.com/someone1/zfsbackup-go/blob/master/integration_test.go#L560) that uses encryption and signatures so I hope that part of the code should be ok!

Thanks for the log but it doesn't seem to be the debug log, can you please try running the command with `--logLevel debug`?

**Comment by acdapkus** [comment]
Sorry for the late response. I am still very interested in finding the solution.

I reran the command with the --logLevel debug

`sudo AWS_ACCESS_KEY=XX AWS_REGION=XX AWS_SECRET_ACCESS_KEY=XX GOROOT=/usr/local/go /usr/local/go/zfsbackup-go receive --encryptTo a.dapkus@XX.com --signFrom a.dapkus@XX.com --publicKeyRingPath public.pgp.asc --secretKeyRingPath private.pgp.asc --logLevel debug --auto -d tank/encryptionTest@testUpload s3://XX.backups tank`

The output looks the same:

```
2020/08/25 19:33:23 Setting number of cores to: 2
2020/08/25 19:33:23 Loaded private key ring private.pgp.asc
2020/08/25 19:33:23 Loaded public key ring public.pgp.asc
2020/08/25 19:33:23 Setting working directory to /root/.zfsbackup
2020/08/25 19:33:23 PGP Debug Info:
Loaded Private Keys:
        XXX
        map[Aleksander Dapkus <a.dapkus@tastechnicalconsulting.com>:0xcXXX]

Loaded Public Keys:
        XXX
        map[Aleksander Dapkus <a.dapkus@tastechnicalconsulting.com>:0xcXXX]
Enter passphrase to decrypt encryption key: 2020/08/25 19:33:25 Limiting the number of active files to 5
2020/08/25 19:33:25 Initializing Backend s3://XXX.backups
2020/08/25 19:33:25 s3 backend: will use the Bulk restore tier when trying to restore from Glacier.
2020/08/25 19:33:25 Could not read manifest /root/.zfsbackup/cache/XXX/XXX due to error - openpgp: invalid data: tag byte does not have MSB set
```

If this is not the expected output from the debug level, could this possible be indicative of an issue?

**Comment by someone1** [comment]
Hmm - it could be that your local cache is corrupt, please rename `/root/.zfsbackup/cache/XXX/XXX` to `/root/.zfsbackup/cache/XXX/XXX.bak` and try again.

**Comment by acdapkus** [comment]
The output did change.

```
2020/08/25 20:13:31 Setting number of cores to: 2
2020/08/25 20:13:31 Loaded private key ring private.pgp.asc
2020/08/25 20:13:31 Loaded public key ring public.pgp.asc
2020/08/25 20:13:31 Setting working directory to /root/.zfsbackup
2020/08/25 20:13:31 PGP Debug Info:
Loaded Private Keys:
        XXX
        map[Aleksander Dapkus <a.dapkus@XXX.com>:0xcXXX]

Loaded Public Keys:
        XXX
        map[Aleksander Dapkus <a.dapkus@XXX.com>:0xcXXX]
Enter passphrase to decrypt encryption key: 2020/08/25 20:13:33 Limiting the number of active files to 5
2020/08/25 20:13:33 Initializing Backend s3://XXX.backups
2020/08/25 20:13:34 s3 backend: will use the Bulk restore tier when trying to restore from Glacier.
2020/08/25 20:13:35 Syncing 1 manifests to local cache.
2020/08/25 20:13:35 Downloaded manifests|tank/s3test|uploadTest.manifest.gz to local cache.
2020/08/25 20:13:35 Could not read manifest /root/.zfsbackup/cache/2a66591e307652ba6fa5e894cef00c43/53e1f2f57e49e04cde3640a591507d19 due to error - openpgp: invalid data: tag byte does not have MSB set

```

I left the cache names in because I doubt these are security concerns, and the off chance they are helpful.

The line `2020/08/25 20:13:35 Could not read manifest` leads me to believe this could be a permissions issue. Does this make sense?

If not the permissions, I can try to reupload the snapshot. How do I best clear my S3 bucket to ensure no issues with this old manifest? I'm just starting out, so I can recreate the bucket if that is recommended.

**Comment by someone1** [comment]
Did you by chance start with unencrypted/signed backups and then switch to them? It seems to be the case. 

Unfortunately the app assumes the parameters passed in for the restore should be applied to all downloaded files, it doesn't currently try to figure out how the files were stored and relies on the user to pass in the correct parameters for the restore.

**Comment by acdapkus** [comment]
Actually, yes! I started out with an unencrypted snapshot upload. I restored it. Then I made a new key to use with this and I started testing encrypted backups.

I will remove the S3 bucket and the cache locally, then start again with encryption. I'll report back.

**Comment by acdapkus** [comment]
Still early in the process of setting up automation and everything, but I am happy to report my issue is fixed!

You were correct. The issue was mixing unencrypted backups and encrypted backups. The fix was to delete the local cache folders and local temp folder, as well as delete the S3 folders. ZFSbackup-go then worked perfectly.

Thanks for all the help! As the issue is resolved, I will mark as closed.
