### ISSUE TITLE
Multiple Concurrent Requests on Receive?

### ISSUE THREAD

**Issue by acdapkus** [someone1/zfsbackup-go#41]
I am looking to speed up the recovery time from S3 to a co-located (at least the same region) EC2 instance. After testing different instance levels, it is my conclusion that the only way to reach the speeds requested is to use multiple concurrent requests to my S3 bucket.

I am aware that concurrent uploads are possible using zfsbackup-go during the "send" phase. I am also aware that aws cli has the ability to make concurrent requests (https://docs.aws.amazon.com/cli/latest/topic/s3-config.html)

> max_concurrent_requests - The maximum number of concurrent requests.
> max_queue_size - The maximum number of tasks in the task queue.
> multipart_threshold - The size threshold the CLI uses for multipart transfers of individual files.
> multipart_chunksize - When using multipart transfers, this is the chunk size that the CLI uses for multipart transfers of individual files.

Is it currently possible to do what I am requesting in zfsbackup-go, and if not, am I missing a key issue with implementing this?

**Comment by someone1** [comment]
this is already a built-in feature, you can specify `--maxFileBuffer` to increase the number of files to download locally at once (default: 5). I think the option help text was copied from the `send` cmd so this needs to be updated. 

You can try updating the limit to see if that helps, but we always need the next file in order so the restore will always wait for it to be finished downloading before moving onto the next file. 

Things you can try to increase the restore speed:
* Increase the `maxFileBuffer` size to download more volumes at once
* Mount your /tmp path to a RAMFS (at least 1GB useable) or make sure your EC2 instance is running with a Local SSD provisioned with enough throughput to get the restore speed you want
* Adjust the volume sizes - keep them big enough to saturate a download link but small enough so you're not restoring faster than you're downloading.
*
Let me know if that helps!
