### ISSUE TITLE
[Feature Request] Use backends in round-robin to add up their capacity.

### ISSUE THREAD

**Issue by gnattu** [someone1/zfsbackup-go#42]
In practice we are going to have pools that went TBs large, and that would beyond the largest capacity of a single storage some backends could offer. If we can use backends in round robin, we are able to add up their capacity and enable us to do full backups for extremely large pools.

**Comment by someone1** [comment]
Can you please elaborate your use case a bit? Most supported backends have no limits (Azure lists 5PiB but lets you request more).

Pools are backed up into multiple objects - referred to as volumes - which by default are ~200 MiB each. You should have no issues backing up petabytes of storage to a single backend supported.

Can you please provide a little more context as to what exact issue you're running into?

* [Google Cloud Storage](https://cloud.google.com/storage/quotas) - Max Object Size: 5TB, No limit to # of objects in a bucket or max bucket size
* [AWS S3 Storage](https://aws.amazon.com/s3/faqs/#:~:text=The%20total%20volume%20of%20data,single%20PUT%20is%205%20gigabytes.) - Max Object Size: 5TB, no limit to # of objects in a bucket or max bucket size
* [Backblaze B2](https://www.backblaze.com/b2/docs/buckets.html) ([here too](https://www.backblaze.com/b2/docs/large_files.html)) - Max Object Size: 10TB, no limit to # of objects in a bucket or max bucket size
* [Azure Blob Storage](https://docs.microsoft.com/en-us/azure/storage/blobs/scalability-targets#scale-targets-for-blob-storage) ([here too](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#storage-limits)) - Max Object Size: 4.75TiB, no limit to # of objects, max storage account size: 5PiB (you can reach out to support to request an increase)
