### ISSUE TITLE
Azure Secure Access Signature support?

### ISSUE THREAD

**Issue by davidchisnall** [someone1/zfsbackup-go#5]
For my use case (off-site backup for a NAS), I have three threat models in mind:

 * Catastrophic physical failure (house burns down, lightning fries my NAS).
 * NAS stolen in break-in.
 * NAS infected with malware.

In the first two cases, I have to assume that everything on the NAS may be compromised.  For encryption I can store only the gpg public key on the machine and store the private key somewhere else, so zfsbackup can write to the backups but can't read them, but that doesn't prevent the Azure account details being compromised and my data being erased (or modified in-situ).  I'd like to be able to generate a SAS with minimum required privileges, so zfsbackup can create new blobs, but can't delete or modify old ones.

**Comment by someone1** [comment]
Thanks for the feature request, it looks like the storage SDK I've been using is on its way out, and a [new one ](https://github.com/Azure/azure-storage-blob-go) is available from the Azure team. This includes SAS support out of the box so I can look into integrating this.

Is your intention to provide a SAS to zfsbackup and generate it outside as needed? It appears you need to provide the account name/key to generate the SAS in the first place so I assume this is your intended use-case. With that in mind, you'll have to know to provide the appropriate SAS/credentials when performing cleanup and restore operations as they'll require more than just Write/List permissions.

**Comment by davidchisnall** [comment]
Thanks!  Yes, I'd aim to generate an SAS for backup and a separate one for restore.  The backup one would allow creation of new blocks, but not deletion or modification, and be used in conjunction with the GPG public key, so if the NAS is compromised then the attacker can't do anything bad to old backups, only new ones and can't decrypt them.  The restore SAS would have read permission and the GPG private key, so it would be able to get and decrypt the backups.  Given how cheap Azure's Archive storage tier is ($2/TB/month), I don't anticipate deleting the data.

**Comment by someone1** [comment]
Just a quick update - been busy with other projects but this is still on my radar - I don't think I'd have time to do a proper test so would you be willing to compile from a dev branch and give it a test for me? I should have time in the next week to tackle this.

**Comment by davidchisnall** [comment]
Sorry for the delayed response.  I can probably test something in the next few weeks, but I don't promise a very quick turnaround at the moment.

**Comment by someone1** [comment]
I decided against switching the Azure Go SDK for this update as it seems like a bigger task that will require more time and planning to make sure I get right. The older Go package is far more intuitive IMHO and getting SAS to work took almost no time at all (in theory).

Do you mind compiling from master and testing out the SAS feature? I'll try and get it to it before releasing a new version myself but it would help to make sure it fits your use case!

**Comment by davidchisnall** [comment]
I should be able to try it this weekend.

I encountered some difficulty configuring the use of Azure (and ended up having to stick some printfs in the code to figure out how to make it work).  The URL for Azure is normally of the form username.home.windows.net/container, but you need it to be specified as just azure://container.  Hopefully SAS use doesn't change this, so as long as I just need to change the environment variables and use a different binary it's easy.

**Comment by someone1** [comment]
Ahh, yes so the container we use will be based off what in the SAS URI (I should probably place a check to ensure the container provided in the send command is the container the SAS URI is authorized for).

Just set the env variable `AZURE_SAS_URI ` to the SAS URI instead of the user/key combination and keep all else the same (e.g. still provide azure://<container> as the destination).

**Comment by someone1** [comment]
By the way, it looks like there are a few ways I've seen passing SAS to applications. I am expecting a valid URL formatted SAS URI as I saw in this [example document](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-dotnet-shared-access-signature-part-2) (e.g.: Container SAS URI: `https://storagesample.blob.core.windows.net/sascontainer?sv=2016-05-31&sr=c&sig=pFlEZD%2F6sJTNLxD%2FQ26Hh85j%2FzYPxZav6mP1KJwnvJE%3D&se=2017-05-16T16%3A16%3A47Z&sp=wl`)

You can compile a custom version by just running `go get -u github.com/someone1/zfsbackup-go`

The compiled binary should be in your $GOPATH/bin directory.

Thanks for helping test!

**Comment by davidchisnall** [comment]
What permissions does the SAS need?  I'm hoping write, list, add and create, and only on blobs?  I would like to be in a position that, if my NAS is compromised, the stolen credentials can't be used to read or delete my off-site backups.  What are the required allowed resource types?

The interface for generating SASs provides a connection string (probably not helpful for you), a SAS token (set of arguments to add to the base URL to describe the access rights) and a URL.  Is it actually useful to provide the full URL, or would the token be easier for your code to work with?

I managed to build from master last weekend, so hopefully I should have no problems (though I do have a zfsbackup-go instance backing up a very large ZFS filesystem, so don't have a huge amount of spare upstream bandwidth!)

**Comment by someone1** [comment]
I believe you'll want to first create a stored access policy on the container for Blobs: Add/Write/List/Create

You'll then want to create a container SAS URI for that policy (thus allowing Add/Write/List/Create access to blobs within that container). I don't believe you can do this via the online Azure Admin Console, you'll need to do this programmatically. Please see [this article](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-dotnet-shared-access-signature-part-2#generate-a-shared-access-signature-uri-on-the-container-that-uses-an-access-policy) for more information.

You'll need to pass the full SAS URL through the `AZURE_SAS_URI` environmental variable.

**Comment by someone1** [comment]
I was able to code the new Azure SDK package but looks like they don't support checksum on upload. I opened tickets with the hopes they'll add it soon!

You can test the new code by compiling off of the [proper branch](https://github.com/someone1/zfsbackup-go/tree/azuresdkupdate).

**Comment by someone1** [comment]
Ahhh, you can just put false values for now, I'll adjust and add a test to catch this

**Comment by someone1** [comment]
I was able to test the new branch with SAS URIs and it looks to be working just fine. The bulk of the code is testable against the blob emulator and the only non-testable code is using SAS vs Shared Key authentication. I did not run into any issues where it was expecting an account key to be defined, just the presence of the AZURE_SAS_URI environmental variable was enough.

I'm pretty happy with the new branch so I'm thinking of merging it soon - let me know if you think you can help test.

**Comment by davidchisnall** [comment]
I haven't had a chance to write the code to generate the second set of keys, unfortunately, and so it currently fails for me.  Do you have any free Azure credit?  Microsoft hands out MSDN subscriptions to some open source developers, and I can ask about getting you on that list if you're not already.

**Comment by someone1** [comment]
I actually do not - if you send me info I can look into it - thanks for the tip!

I have a pay-as-you-go plan and was able to test using SAS URIs with that for a small dataset. The Microsoft Azure Storage Explorer available on Windows can generate the SAS URI for you. I created an access policy on my container with Write/List capabilities and generated a SAS URI on that policy.

**Comment by davidchisnall** [comment]
Can you drop me an email (first name dot last name at microsoft.com)?  It looks as if we can set something up.
